language: objective-c
xcode_workspace: nanou-ios.xcworkspace
xcode_scheme: nanou-ios
xcode_sdk:
  - iphonesimulator

matrix:
  include:
    - osx_image: xcode8
    - osx_image: xcode8.1
    - osx_image: xcode8.2

before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build | xcpretty
