language: objective-c
osx_image: xcode8
xcode_workspace: nanou-ios.xcworkspace
xcode_scheme: nanou-ios
xcode_sdk:
    - iphonesimulator

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build
  # - xctool -project nanou-ios.xcodeproj -scheme nanou-ios -sdk iphonesimulator10.0 build test
